### PR TITLE
Added kill sensory neuron (#2)

### PR DESCRIPTION
**Pull request by bolshoytoster**
Added two new sensors, KILLS & SELF_KILLS.
KILLS returns the total number of kills of individuals in the area divided by the total kills.
SELF_KILLS returns the current individual's kills divided by the total kills.

These are both disabled by default, because the KILL_FORWARD action is and you could probably
get rid of SELF_KILLS since it's not as useful.

I've also made the murderCount variable in simulator.cpp global so it can be accessed in getSensor.cpp.

### CODE REVIEW

**Comment by Sismars19** [comment]
Hi, how are you? Do you want to have a good investment ? please click this one, thank you very much

https://vuuzletvph.com/what-is-the-secret-of-nft-tokens-and-why-they-are-bought-for-millions-of-dollars/

What is the secret of NFT tokens and why they are bought for millions of dollars - Vuuzle.TV Philippines
vuuzletvph.com

What is the secret of NFT tokens and why they are bought for millions of dollars - Vuuzle.TV Philippines
vuuzletvph.com

**Comment by davidrmiller** [comment]
I've been playing around with this PR and I like the concept of the new kill sensors, but there are details that need further thought.

This PR relies on the global variable murderCount, but murderCount is only an approximation. It is incremented at the end of each sim step by the size of the deferred death queue. A single individual can be queued for death multiple times if it is killed by multiple neighbors during the same sim step. The size of the death queue therefore is equal to or greater than the number of unique individuals actually deceased.

This PR introduces the new member variable Indiv::kills to count the number of murders committed by each individual. It is incremented in executeActions.cpp when an individual causes another individual to be queued for death. However, since the same individual can be queued for death by multiple murderers, multiple killers get charged for the same kill.

The result is that Indiv::kills and the global murderCount are only approximations. In getSensor.cpp, handlers for the new KILLS and SELF_KILLS sensors compute a sensor value from these approximations. In the case of KILLS, the sensor could, in theory, overflow the allowable limits of the sensor value range.

The global murderCount is even less meaningful when the "radioactive" challenge is enabled. This is because murderCount is derived from the size of the death queue which includes individuals who die non-violently.

Before we introduce these new sensors, I'd like to solve two problems: (1) find a way to compute an exact count of individuals killed by murder, and (2) determine what to do when multiple murderers kill the same individual.

**Comment by bolshoytoster** [comment]
This could be resolved if murderCount is instead incremented when the indivs are killed, in `Peeps::drainDeathQueue`:

https://github.com/davidrmiller/biosim4/blob/2310473213783df3c14ff7d7d14d7da6774fc8b5/src/peeps.cpp#L42-L52

This could be changed to:
```c++
void Peeps::drainDeathQueue() 
{
    for (uint16_t index : deathQueue) {
        if (indiv.alive) {
            auto & indiv = peeps[index];
            grid.set(indiv.loc, 0);
            indiv.alive = false;
            ++murderCount
        }
    }
    deathQueue.clear();
}
```

Then obviously remove `murderCount += peeps.deathQueueSize(); ` from line 146 of `simulation.cpp`

---

Regarding environmental deaths, if we want to not count them we’d have to do something different. In `executeActions` - at `Action::KILL_FORWARD `:
https://github.com/davidrmiller/biosim4/blob/2310473213783df3c14ff7d7d14d7da6774fc8b5/src/executeActions.cpp#L125-L141

Just before `peeps.queueForDeath(indiv2)` we’d have to make sure `indiv2.index` isn’t in `deathQueue`. A quick [stackoverflow](https://stackoverflow.com/a/5998594) search says it won’t be hard - but it would probably be inefficient to search the whole queue each time an indiv is killed, so I’d just leave it as the above suggestion.

**Comment by petterreinholdtsen** [comment]
Any hope to have this branch rebased on the latest main to make it easier to test?

**Comment by bolshoytoster** [comment]
@petterreinholdtsen I'll do that now.

**Comment by petterreinholdtsen** [comment]
@bolshoytoster Did you give up getting this change into the main branch, or was there some other reason you closed this pull request?

**Comment by bolshoytoster** [comment]
@petterreinholdtsen I gave up, since there was no activity on the PR for over a year.

**Comment by petterreinholdtsen** [comment]
[bolshoytoster]
> @petterreinholdtsen I gave up, since there was no activity on the PR
> for over a year.

I do not blame you.

I've had bugs I reported fixed and patches I provied applied more than
10 years later, and while I did give up in the mean time, I was very
happy when the fix finally was published for everyone to use.  I am glad
I left the patch and bug report open even though I gave up, as someone
new might take over some time in the future to find the issue.

-- 
Happy hacking
Petter Reinholdtsen

**Pull request closed without merging**
