### PR TITLE
Rewrote Makefile to a simpler and hand made edition

### PR DESCRIPTION
**Pull request by petterreinholdtsen**
Build binary using all source files src/*.cpp, and let them depend on all
src/*.h, and only build either release or debug builds, not both.

This include the fixes from pull requests #67 and #68, and provide a fix
for issue #65.

### CODE REVIEW

**Comment by davidrmiller** [comment]
This is huge improvement over the auto-generated Makefile. Thank you for doing this.

I think it would be nice to add make targets "debug" and "release" because they have been documented elsewhere, we have a history of using them, and they're convenient.

I'm not sure that the header file prerequisite rule is working as intended. For a quick test, I updated a header file but no files got re-built.

**Comment by petterreinholdtsen** [comment]
[David R. Miller]
> This is huge improvement over the auto-generated Makefile. Thank you
> for doing this.

Happy to help. :)

> I think it would be nice to add make targets "debug" and "release"
> because they have been documented elsewhere, we have a history of
> using them, and they're convenient.

OK.  Done.

> I'm not sure that the header file prerequisite rule is working as
> intended. For a quick test, I updated a header file but no files got
> re-built.

Good catch.  I had adjusted that rule since I tested it.  Fixed.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by davidrmiller** [comment]
Very nice, the header dependencies are working.

Putting the object files in the src/ directory resulted in some surprises. Consider this sequence of operation:

make clean
make release
make debug

That caused bin/Debug/biosim4 to be built from the release object files.

**Comment by petterreinholdtsen** [comment]
[David R. Miller]
> Putting the object files in the src/ directory resulted in some
> surprises. Consider this sequence of operation:
>
> make clean
> make release
> make debug
>
> That caused bin/Debug/biosim4 to be built from the release object
> files.

Right.  Better do 'clean' between release and debug builds as I am not
sure how to avoid the problem.

-- 
Happy hacking
Petter Reinholdtsen

**Comment by davidrmiller** [comment]
The old Makefile handled that by maintaining separate obj/Debug and obj/Release directories. I tweaked your Makefile to do the same and made branch #72 to test it.

**Comment by petterreinholdtsen** [comment]
[David R. Miller]
> The old Makefile handled that by maintaining separate obj/Debug and
> obj/Release directories. I tweaked your Makefile to do the same and
> made branch #72 to test it.

Great.

Had a look at that branch, and suspect it would be best to remove the
obj directory in 'clean' and create it during build instead of requiring
obj/Debian and obj/Release to exist before the build.  It would also be
nice to support building from a directory of ones own choosing like
cmake and automake allows, as it allow parallel build for several
architectures in the same network mounted directory.

Come to think of it, what is the point of maintaining both make and
cmake build systems, why not only use cmake and drop the Makefile?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Is this pull request still useful?  I notice is has not been merged yet and this make me wonder if it will ever happen.

**Comment by davidrmiller** [comment]
Sorry for the slow movement of this PR. I was hoping to see some community responses to the concerns you raised in previous comments. But since there has been no comments on this issue or in #72, I'll merge the branch and see what happens :-)

**Pull request closed without merging**
